In [17]:
import pandas as pd
import openpyxl

In [3]:
data = {
    'country' : ['India','England','France'],
    'capital' : ['NewDelhi','London','Paris'],
    'currency' : ['Rupee','Pound','Franc']
}

In [4]:
info_df = pd.DataFrame(data)

In [8]:
for row in info_df.itertuples():
    print(row)

<class 'pandas.core.frame.Pandas'>
<class 'pandas.core.frame.Pandas'>
<class 'pandas.core.frame.Pandas'>

In [11]:
for row_index,row in info_df.iterrows():
    print(row_index)
    print(row)

0
country        India
capital     NewDelhi
currency       Rupee
Name: 0, dtype: str
1
country     England
capital      London
currency      Pound
Name: 1, dtype: str
2
country     France
capital      Paris
currency     Franc
Name: 2, dtype: str

In [14]:
for key,value in info_df.items():
    print(key)
    print(f"{value}\n")

country
0      India
1    England
2     France
Name: country, dtype: str

capital
0    NewDelhi
1      London
2       Paris
Name: capital, dtype: str

currency
0    Rupee
1    Pound
2    Franc
Name: currency, dtype: str

In [18]:
info_df.to_excel('datasets/info_df.xlsx',index=False)

In [19]:
info_df.to_csv('datasets/info_df.txt',index=False)

In [22]:
info_df.to_json('datasets/info_df.json')

In [23]:
info_df.to_html('datasets/info_df.html',index=False)

In [24]:
unsorted = pd.read_csv('datasets/echocardiogram.csv')
unsorted = unsorted[:15]

In [26]:
unsorted.index = [5,6,7,8,9,9,1,2,3,4,10,11,12,13,14]

In [27]:
unsorted

,survival,alive,age,pericardialeffusion,fractionalshortening,epss,lvdd,wallmotion-score,wallmotion-index,mult,name,group,aliveat1
5,11.0,0.0,71.0,0.0,0.260,9.000,4.600,14.0,1.000,1.000,Hendrik,1,0.0
6,19.0,0.0,72.0,0.0,0.380,6.000,4.100,14.0,1.700,0.588,Abraham,1,0.0
7,3.0,1.0,NaN,0.0,NaN,12.000,NaN,6.0,3.000,0.140,Candi,2,NaN
8,16.0,0.0,55.0,0.0,0.260,4.000,3.420,14.0,1.000,1.000,Adam,1,0.0
9,57.0,0.0,60.0,0.0,0.253,12.062,4.603,16.0,1.450,0.788,Barret,1,0.0
9,19.0,1.0,57.0,0.0,0.160,22.000,5.750,18.0,2.250,0.571,Axel,1,0.0
1,26.0,0.0,68.0,0.0,0.260,5.000,4.310,12.0,1.000,0.857,Bailey,1,0.0
2,13.0,0.0,62.0,0.0,0.230,31.000,5.430,22.5,1.875,0.857,Cesar,1,0.0
3,50.0,0.0,60.0,0.0,0.330,8.000,5.250,14.0,1.000,1.000,Keith,1,0.0
4,19.0,0.0,46.0,0.0,0.340,0.000,5.090,16.0,1.140,1.003,Davon,1,0.0
10,25.0,0.0,54.0,0.0,0.140,13.000,4.490,15.5,1.190,0.930,Ferd,1,0.0
11,10.0,1.0,77.0,0.0,0.130,16.000,4.230,18.0,1.800,0.714,Dyson,1,1.0
12,52.0,0.0,62.0,1.0,0.450,9.000,3.600,16.0,1.140,1.003,Elvin,1,0.0
13,52.0,0.0,73.0,0.0,0.330,6.000,4.000,14.0,1.000,1.000,Galen,1,0.0
14,44.0,0.0,60.0,0.0,0.150,10.000,3.730,14.0,1.000,1.000,Hyatt,1,0.0

In [30]:
unsorted.sort_index().sort_index(axis=1)

,age,alive,aliveat1,epss,fractionalshortening,group,lvdd,mult,name,pericardialeffusion,survival,wallmotion-index,wallmotion-score
4,46.0,0.0,0.0,0.000,0.340,1,5.090,1.003,Davon,0.0,19.0,1.140,16.0
10,54.0,0.0,0.0,13.000,0.140,1,4.490,0.930,Ferd,0.0,25.0,1.190,15.5
8,55.0,0.0,0.0,4.000,0.260,1,3.420,1.000,Adam,0.0,16.0,1.000,14.0
9,57.0,1.0,0.0,22.000,0.160,1,5.750,0.571,Axel,0.0,19.0,2.250,18.0
3,60.0,0.0,0.0,8.000,0.330,1,5.250,1.000,Keith,0.0,50.0,1.000,14.0
9,60.0,0.0,0.0,12.062,0.253,1,4.603,0.788,Barret,0.0,57.0,1.450,16.0
14,60.0,0.0,0.0,10.000,0.150,1,3.730,1.000,Hyatt,0.0,44.0,1.000,14.0
2,62.0,0.0,0.0,31.000,0.230,1,5.430,0.857,Cesar,0.0,13.0,1.875,22.5
12,62.0,0.0,0.0,9.000,0.450,1,3.600,1.003,Elvin,1.0,52.0,1.140,16.0
1,68.0,0.0,0.0,5.000,0.260,1,4.310,0.857,Bailey,0.0,26.0,1.000,12.0
5,71.0,0.0,0.0,9.000,0.260,1,4.600,1.000,Hendrik,0.0,11.0,1.000,14.0
6,72.0,0.0,0.0,6.000,0.380,1,4.100,0.588,Abraham,0.0,19.0,1.700,14.0
13,73.0,0.0,0.0,6.000,0.330,1,4.000,1.000,Galen,0.0,52.0,1.000,14.0
11,77.0,1.0,1.0,16.000,0.130,1,4.230,0.714,Dyson,0.0,10.0,1.800,18.0
7,NaN,1.0,NaN,12.000,NaN,2,NaN,0.140,Candi,0.0,3.0,3.000,6.0

In [31]:
unsorted.sort_index().sort_index(axis=1).sort_values(by = 'age')
help(unsorted.merge)

Help on method merge in module pandas.core.frame:

merge(
    right: DataFrame | Series,
    how: MergeHow = 'inner',
    on: IndexLabel | AnyArrayLike | None = None,
    left_on: IndexLabel | AnyArrayLike | None = None,
    right_on: IndexLabel | AnyArrayLike | None = None,
    left_index: bool = False,
    right_index: bool = False,
    sort: bool = False,
    suffixes: Suffixes = ('_x', '_y'),
    copy: bool | lib.NoDefault = <no_default>,
    indicator: str | bool = False,
    validate: MergeValidate | None = None
) -> DataFrame method of pandas.DataFrame instance
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross', 'left_anti', 'right_anti'},
        default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
        * left_anti: use only keys from left frame that are not in right frame, similar
          to SQL left anti join; preserve key order.

          .. versionadded:: 3.0
        * right_anti: use only keys from right frame that are not in left frame, similar
          to SQL right anti join; preserve key order.

          .. versionadded:: 3.0
    on : Hashable or a sequence of the previous
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : Hashable or a sequence of the previous, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : Hashable or a sequence of the previous, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default False
        This keyword is now ignored; changing its value will have no
        impact on the method.

        .. deprecated:: 3.0.0

            This keyword is ignored and will be removed in pandas 4.0. Since
            pandas 3.0, this method always returns a new object using a lazy
            copy mechanism that defers copies until necessary
            (Copy-on-Write). See the `user guide on Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            for more details.

    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

In [37]:
for row in unsorted[['age','alive']].iterrows():
    print(row[1])

age      71.0
alive     0.0
Name: 5, dtype: float64
age      72.0
alive     0.0
Name: 6, dtype: float64
age      NaN
alive    1.0
Name: 7, dtype: float64
age      55.0
alive     0.0
Name: 8, dtype: float64
age      60.0
alive     0.0
Name: 9, dtype: float64
age      57.0
alive     1.0
Name: 9, dtype: float64
age      68.0
alive     0.0
Name: 1, dtype: float64
age      62.0
alive     0.0
Name: 2, dtype: float64
age      60.0
alive     0.0
Name: 3, dtype: float64
age      46.0
alive     0.0
Name: 4, dtype: float64
age      54.0
alive     0.0
Name: 10, dtype: float64
age      77.0
alive     1.0
Name: 11, dtype: float64
age      62.0
alive     0.0
Name: 12, dtype: float64
age      73.0
alive     0.0
Name: 13, dtype: float64
age      60.0
alive     0.0
Name: 14, dtype: float64

In [39]:
companies = {'compnay': ["apple","amazon","facebook"],
       'ceo': ["tim","jeff","mark"]}
comp_ceo = pd.DataFrame(companies)

In [47]:
for row in comp_ceo.iterrecords():
    print(row.ceo)

AttributeError: 'DataFrame' object has no attribute 'iterrecords'